# ---
# - name: Upgrade Java to version 19
#   hosts: '{{ hostname | default("github_runners") }}'
#   become: yes
#   ###### This ansible-playbook is tested with Ubuntu 22.04 ######
#   tasks:
#     # Ensure Java is installed and at the specific version
#     - name: Check if Java is installed
#       command: java -version
#       register: java_check
#       ignore_errors: yes

#     - name: Install Java if not present or at a different version
#       apt:
#         name: openjdk-19-jre-headless  # Replace with the desired Java version package name
#         state: present
#       when: java_check.rc != 0 or '"19."' not in java_check.stderr  # Check Java version

---
- name: Upgrade Java to version 19
  hosts: '{{ hostname | default("github_runners") }}'
  become: yes
  
  # This ansible-playbook is tested with Ubuntu 22.04
  tasks:
    # Check if Java is already installed
    - name: Check if Java is installed
      command: java -version
      register: java_check
      ignore_errors: yes

    # Install Java if not present or at a different version
    - name: Install Java if not present or at a different version
      apt:
        name: openjdk-19-jre-headless  # Replace with the desired Java version package name
        state: present
      when: java_check.rc != 0 or '"19."' not in java_check.stderr  # Check Java version
